# Generated by Django 3.2.2 on 2021-05-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='picture')),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
